//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sandboxWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookmaker
    {
        public int BookmakerId { get; set; }
        public string BookmakerName { get; set; }
    }
}
