//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sandboxWeb.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class omproEntities : DbContext
    {
        public omproEntities()
            : base("name=omproEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bookmaker> Bookmakers { get; set; }
        public virtual DbSet<Competition> Competitions { get; set; }
        public virtual DbSet<CompetitionsNotFound> CompetitionsNotFounds { get; set; }
        public virtual DbSet<ExchangeMatch> ExchangeMatches { get; set; }
        public virtual DbSet<ExchangeRace> ExchangeRaces { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TeamsNotFound> TeamsNotFounds { get; set; }
        public virtual DbSet<Error> Errors { get; set; }
    }
}
